### ISSUE TITLE
Broken dependency on 'type'

### ISSUE THREAD

**Issue by dobesv** [component/querystring#15]
I'm not sure what require('type') is supposed to return, but for me it doesn't seem to work at all:

```
$ node
> require('type')
Error: Cannot find module 'type'
```

Installing `type` from npm doesn't help, that module doesn't conform to the interface used in here.

**Comment by stephenmathieson** [comment]
Yep, it's for a legacy build tool. [This](https://github.com/component/querystring/blob/master/package.json#L10) tells bundlers what to do, so you shouldn't have any issues using this package in your project.

**Comment by dobesv** [comment]
I'm not using a bundle, I'm just importing it from some code, so it breaks.

**Comment by dschmidtadv** [comment]
I am wondering why this still is not fixed. The workaround works, but it's a hack after all.

**Comment by stephenmathieson** [comment]
The majority of the packages in the `component` organization are in "maintenance mode only". We're not actively adding features or "fixing hacks". The last commit in this project was several years ago. If you're still using this package, I **strongly** recommend you migrate to one of the dozens of better maintained/battle-tested JavaScript query string parsers. Some examples:

- https://www.npmjs.com/package/qs
- https://www.npmjs.com/package/querystring
- https://www.npmjs.com/package/query-string

If migrating is not an option for you, and something here is _actually broken_ (without a workaround/solution), let me know and I'll see if I can figure out a fix.

**Comment by dobesv** [comment]
I think part of the problem is that this could be an indirect dependency of something we use, so we can't so easily eliminate it.

**Comment by stephenmathieson** [comment]
Yep, understood. As suggested, I'm happy to fix _actual problems_ (eg #16). Unfortunately I don't have time to remove build hacks, but I do have time to review the occasional PR 😉
